version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app # Mount the current directory to the container for live updates
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
