name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        run: |
          docker --version
          docker compose --version

      # Build the Docker images
      - name: Build Docker images
        run: make build

      # Run tests
      - name: Run tests
        run: make test

      # Run linting
      - name: Run linting
        run: make lint

      # Run formatting
      - name: Run formatting
        run: make format

      # Clean up project-specific Docker resources
      - name: Clean up project-specific Docker resources
        run: make clean